# Generated by Django 5.1.1 on 2024-09-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productvariant_sku_alter_productvariant_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
