# Generated by Django 5.1.1 on 2024-09-26 05:22

import products.models
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_ppoi',
            field=models.CharField(default='0.5x0.5', max_length=50),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_ppoi',
            field=models.CharField(default='0.5x0.5', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=products.models.upload_image_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(default=1, upload_to=products.models.upload_image_path, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
