# Generated by Django 5.1.1 on 2024-09-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_image_ppoi_productvariant_image_ppoi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_ppoi',
            field=models.CharField(default=(0.5, 0.5), max_length=50),
        ),
    ]
