# Generated by Django 5.1.1 on 2024-09-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_productvariant_image_ppoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='num_reviews',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
