# Generated by Django 5.1.1 on 2024-09-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productvariant_num_reviews_productvariant_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='num_reviews',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=2, null=True),
        ),
    ]
