# Generated by Django 5.1.1 on 2024-10-03 04:58

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_productimage_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantimage',
            name='image_ppoi',
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='image',
            field=models.ImageField(upload_to=products.models.upload_image_path),
        ),
    ]
