# Generated by Django 5.1.1 on 2024-10-03 08:31

import products.models
import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_productimage_image_ppoi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'),
        ),
        migrations.AddField(
            model_name='productvariantimage',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Image PPOI'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to=products.models.upload_image_path, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='productvariantimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to=products.models.upload_image_path, verbose_name='Image'),
        ),
    ]
